#ifndef _WNDSTYPE_H
#define _WNDSTYPE_H

//该文件主要用来定义窗口的类型
//窗口的类型是用来快速识别窗口的标识
typedef enum euWndsType
{
	WND_ALL     = 0,   //所有窗口
	WND_MAINMAP,
	WND_CHILDMAP,
	WND_STRIP,
	WND_SETUP,
	WND_INFO,
	WND_QNH,
	WND_STCA,
	WND_DAIW,
	WND_MSAW,
	WND_MIL,
	WND_RWY,
	WND_RAM,
	WND_CLAM,
	WND_SHOT_POINT,
	WND_RVSM_AREA,

	//////////////////////////////////////////////////////////////////////////
	//begin 管制员席位窗口
	CONTROLLER_TOPWND,
	CONTROLLER_BOTTOMWND,
	SETTINGWND,
	FPLLISTWND,  
	MAPSETTINGWND,
	FPLWND,
	HOLDWND,
	GATEQUERYWND,
    WAITLISTWND,
	SECTORALLOCATEWND,
	HOLDSETTINGWND,
	ALARMWND,
	SYSTEMINFOWND,
	LABELRIGHTMENU, // 标牌右键菜单
	LABELDATAEDIT,  // 标牌自由文本编辑
	CFLSETTINGWND,  // 右键CFL设置窗口
    WND_RADTAG, //Rad Tag Wnd    
	WND_TAGLIST, // Tag List Wnd
    SECTORFILTERWND,//扇区过滤窗口	
	STRIPCONFIGRATIONSETUPWND,
	WND_SECTOR, // 扇区选择窗口
	ALARMSOUNDWND, //告警声音设置窗口
	WND_COASTLIST, //盲区列表
	WND_CONNECT,   //网络连接状态窗口
	//end
	//////////////////////////////////////////////////////////////////////////

	//////////////////////////////////////////////////////////////////////////
	//begin 机长席位窗口
	PILOT_BOTTOMWND,
	PILOT_TOPWND,
	PILOT_CMDPANEL,
	PILOT_MAP_CMDWND,
	PILOT_INFO_CMDWND,
	PILOT_MAP_RESPONSEWND,
	PILOT_INFO_RESPONSEWND,
	PILOT_CURAIRCRAFTINFOWND,
	PILOT_CURVEHICLEINFOWND,
	PILOT_FPLLISTWND,
	PILOT_VEHICLELISTWND,
	PILOT_QUREYRESULTWND,
	PILOT_REPORTWND,
	PILOT_REPROTACKWND,
	PILOT_MOUSECMDWND,
	DEFINE_CMD,
	HOLDLIST,
	CANCELEDLIST,
	VEHICLELIST,
	HISTORYCMDWND,
	STRIPBAYWND,
	PILOTMAPWND,
	PILOTINFOWND,
	STATUSWND,
	PILOT_SECTORFILTERWND,
	PILOT_LABELFORMATSETWND,
	PILOT_MAILREPORT,
	PILOT_TITLE,
	PILOT_COLORSETTINGWND,
	PILOT_EXIT,
	PILOT_TAXWND,
	//end 
	//////////////////////////////////////////////////////////////////////////

	//////////////////////////////////////////////////////////////////////////
	//begin 教员席位窗口
	SUPERVISOR_TOPWND,
	SUPERVISOR_BOTTOMWND,
	SUPERVISOR_EXERCISECTRLWND,
	SUPERVISOR_MAPSETTINGWND,
	SUPERVISOR_FPLLISTWND,
	SUPERVISOR_FPLWND,
	SUPERVISOR_GATEASSIGNWND,
	SUPERVISOR_LIGHTCTRL,
	SUPERVISOR_TIMEMODIFYWND,
	SUPERVISOR_WEATHERINFOWND,
	SUPERVISOR_ATCSETTINGWND,
	SUPERVISOR_MAILSENDWND,
	SUPERVISOR_ASSISTWND,
	//end 
	//////////////////////////////////////////////////////////////////////////

	WND_CMDWND,
	WND_SECONDMAP,
	WND_COLOR,
	WND_COLOR_SETTINGS,
	WND_SYS_SETTINGS,
	WND_FLYPLAN,
	WND_GLYPH_CREATOR,
	WND_ILS,
	WND_MAIL,
	WND_ENVCTRL,
	WND_AIRPORTENV,
	WND_RUNWAYENV,
	WND_VIEW,
	WND_EFFECT,
	WND_CLOUD,
	WND_MOTIONALSUBWND,
	WND_RADARSETTINGWND,
	WND_TLSETTING,
	WND_CREATEPLANE,
	WND_END
}WndsType;


//定义窗口的布局方式，暂时处理三种模式
//管制员 
//机长
//教员
typedef enum euLayoutType
{
	LAYOUT_SUPERVISOR,
	LAYOUT_PILOT,
	LAYOUT_CONTROLLER,
}LayoutType;


#endif
